config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :admin_users
    resources :working_days

    root to: 'users#index'
  end
  
  resources :working_days
  devise_for :users
  root to: 'dashboard#index'
  get 'users', to: 'dashboard#show'
end

app/models/admin_user.rb
# Using STI for share users table between users and admin
class AdminUser < User; end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # User cannot be created without name and last_name
  validates_presence_of :name, :last_name

  has_many :working_days

  # Search function
  def self.search(search)
    key = "%#{search}%"
    if search
      where(["name ILIKE :search OR last_name ILIKE :search OR email ILIKE :search OR gender ILIKE :search", search: key])
    else
      false
    end
  end

  # Display full name
  def full_name
    last_name.capitalize + ', ' + name.capitalize
  end
end

app/models/working_day.rb
class WorkingDay < ApplicationRecord
  belongs_to :user

  # Checkin must be present in working day
  validates_presence_of :checkin

  # TODO: Refactor lambda
  scope :user_filter, ->(user) { 
    if user.type == 'AdminUser'
      WorkingDay.all.newer_first
    else
      WorkingDay.where(user_id: user.id).newer_first
    end
  }

  # Sort items for working days from newest to oldest
  scope :newer_first, -> { order(created_at: :desc) }

  # Calculate worked minutes or hours for working_day
  def worked_time
    # If check out not nil calculate time else no time to calculate
    if !checkout.nil?
      time = ((checkout - checkin) / 1.hour).round
      if time >= 1
        time.to_s + ' hours.'
      else
        ((checkout - checkin) / 60).round.to_s + ' minutes.'
      end
    else
      '0 time.'
    end
  end
end

app/controllers/admin/admin_users_controller.rb
module Admin
  class AdminUsersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  # Method to ask for admin types
  def self.admin_types
    ['AdminUser']
  end

  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_user!
    before_action :authenticate_admin

    def authenticate_admin
      # Authentication logic
      unless Admin.admin_types.include?(current_user.try(:type))
        redirect_to root_path
      end
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/working_days_controller.rb
module Admin
  class WorkingDaysController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index; end

  def show
    @users = User.search(params[:search])
  end
end

app/controllers/working_days_controller.rb
class WorkingDaysController < ApplicationController
  before_action :set_working_day, only: %i[show]

  def index
    @working_days = WorkingDay.user_filter(current_user)
  end

  def new
    @working_day = WorkingDay.new
  end

  def create
    @working_day = WorkingDay.new(working_day_params)
    @working_day.user_id = current_user.id

    if @working_day.save
      redirect_to working_days_path, notice: 'You make check! :)'
    else
      render :new
    end
  end

  def show; end

  private

  def working_day_params
    params.require(:working_day).permit(:checkin, :checkout)
  end

  def set_working_day
    @user_working_days = WorkingDay.where(user_id: params[:id])
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Implemented helper methods to ask if an user is an admin
  def admin_types
    ['AdminUser']
  end

  def employee?
    !admin?
  end

  def admin?
    admin_types.include?(current_user.type)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  # Give format to user name
  def format_name
    current_user.name.capitalize
  end
end

app/helpers/working_days_helper.rb
module WorkingDaysHelper
  # Helper method to format Datetime data in working days view
  def check_format(datetime, type)
    if datetime.nil?
      # In case an employee has not checked out yet
      'No check out yet'
    elsif type == 'date'
      # For date | Month - Day - Year
      datetime.strftime('%B - %d - %y')
    elsif type == 'time'
      # For check | Hour : Minute, Meridian
      datetime.strftime('%H : %M, %p')
    end
  end
end

app/views/dashboard/_checkin_jumbotron.html.erb
<div class="jumbotron">
  <a class="btn btn-success btn-lg btn-block" href="#" role="button">Check In</a>
  <br>
  <a class="btn btn-secondary btn-lg btn-block" href="#" role="button">Check Out</a>
</div>

app/views/dashboard/_links.html.erb
<ul class="nav">
  <li class="nav-item">
    <%= link_to 'Show checkins', working_days_path, class: 'nav-link' %>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Generate Report</a>
  </li>
</ul>

app/views/dashboard/_search.html.erb
<div class="container dashboard-search">
  <%= form_tag users_path, method: :get do %>
  <div class="form-group">
    <%= text_field_tag :search, params[:search], class: "form-control", placeholder: 'Search Names, Emails, By Gender' %>
  </div>
    <%= submit_tag 'Search', :name => nil, class: 'btn btn-success' %>
  <% end %>
</div>

app/views/dashboard/index.html.erb
<h1>Welcome <%= format_name %>!</h1>

<p class="lead">
  Make Check In and have a nice day! 
</p>

<hr>

  <%= render 'search' if admin? %>

  <%= render 'checkin_jumbotron' if employee? %>

<br>

<%= render 'links' %>

app/views/dashboard/show.html.erb
<h2>Found Employees</h2>

<table class="table table-striped mt-3">
  <thead>
    <tr>
      <th scope="col">Full Name</th>
      <th scope="col">Gender</th>
      <th scope="col">Email</th>
    </tr>
  </thead>
  <tbody>

    <% @users.each do |user| %>
      <tr>
        <th scope="row">
          <%= link_to user.full_name, working_day_path(id: user.id), class: 'text-primary' %>
        </th>
        <td>
          <%= user.gender.try(:capitalize) %>
        </td>
        <td>
          <%= user.email %>
        </td>
      </tr>
    <% end %>

  </tbody>
</table>


<%= link_to 'Back', :back %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Employeesapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'shared/bootstrap' %>
  </head>

  <body style="height: 100vh !important;">

    <%= render 'shared/navbar' %>

    <!-- Flash Messages -->
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-primary" %>
    <% end %>

    <div class="container mt-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_bootstrap.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <h2 class="navbar-brand" >Employees Runa</h2>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">

      <li class="nav-item active">
        <%= link_to 'Dashboard', root_path, class: 'nav-link' %>
      </li>


      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'Edit', edit_user_registration_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
      </li>
      <% end %>

    </ul>
  </div>
</nav>

app/views/working_days/_form.html.erb
<%= form_for @working_day do |f| %>
  <% if @working_day.errors.any? %>
    <% @working_day.errors.full_messages.each do |error| %>
    <ul>
      <% @working_day.errors.full_messages.each do |msg| %>
      <li><%= msg  %></li>
      <% end %>
    </ul>
    <% end%>
  <% end %>

  <div class="form-group">
    <%= f.label :checkin %>
    <%= f.datetime_field :checkin, class: "form-control form-control-lg" %>
  </div>
  <div class="form-group">
    <%= f.label :checkout %>
    <%= f.datetime_field :checkout, class: "form-control form-control-lg" %>
  </div>

  <%= f.submit 'Save', class: "btn btn-primary btn-block" %>
<% end %>

app/views/working_days/index.html.erb
<h1>History of the workday</h1>

<table class="table table-striped mt-3">
  <thead>
    <tr>
      <th scope="col">Full Name</th>
      <th scope="col">Date</th>
      <th scope="col">Check In</th>
      <th scope="col">Check Out</th>
      <th scope="col">Worked Hours</th>
    </tr>
  </thead>
  <tbody>

    <%# WorkingDay Object:  %>
    <%# WorkingDay id: 5, checkin: "2020-02-15 13:00:00", checkout: "2020-02-15 15:00:00", user_id: 2, created_at: "2020-02-11 21:35:13", updated_at: "2020-02-11 21:35:13" %>


    <% @working_days.each do |day| %>
      <tr>
        <th scope="row">
          <%# If current_user is admin, must see link for specific user, if is a employee cannot see the link %>
          <%= link_to day.user.full_name, working_day_path(id: day.user.id), class: 'text-primary' if admin? %>
          <%= day.user.full_name if employee? %>
        </th>
        <td><%= check_format(day.checkin, 'date') %></td>
        <td><%= check_format(day.checkin, 'time') %></td>
        <td><%= check_format(day.checkout, 'time') %></td>
        <td><%= day.worked_time %></td>
      </tr>
    <% end %>

  </tbody>
</table>

app/views/working_days/new.html.erb
<h2>Register your time job</h2>

<%= render 'form' %>

app/views/working_days/show.html.erb
<h1>History of <%= @user.full_name %></h1>

<table class="table table-striped mt-3">
  <thead>
    <tr>
      <th scope="col">Date</th>
      <th scope="col">Check In</th>
      <th scope="col">Check Out</th>
      <th scope="col">Worked Time</th>
    </tr>
  </thead>
  <tbody>
    <% @user_working_days.each do |day| %>
      <tr>
        <th scope="row"><%= check_format(day.checkin, 'date') %></th>
        <td><%= check_format(day.checkin, 'time') %></td>
        <td><%= check_format(day.checkout, 'time') %></td>
        <td><%= day.worked_time %></td>
      </tr>
    <% end %>
  </tbody>
</table>